create table
  public.potions (
    id integer generated by default as identity,
    sku text null,
    num_red integer null,
    num_green integer null,
    num_blue integer null,
    num_dark integer null,
    quantity integer null,
    price integer null,
    constraint potions_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.global_inventory (
    num_red_potions integer generated by default as identity,
    num_red_ml integer not null,
    gold integer null,
    num_green_potions integer null,
    num_blue_potions integer null,
    num_green_ml integer null,
    num_blue_ml integer null,
    id integer generated by default as identity,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.carts (
    id integer generated by default as identity,
    constraint carts_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.cart_items (
    id bigint generated by default as identity,
    cart_id integer null,
    potion_id integer null,
    quantity integer null default 0,
    constraint cart_items_pkey primary key (id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references carts (id),
    constraint cart_items_potion_id_fkey foreign key (potion_id) references potions (id)
  ) tablespace pg_default;