create table
  public.cart_items (
    id bigint generated by default as identity,
    cart_id integer null,
    potion_id integer null,
    quantity integer null default 0,
    timestamp timestamp without time zone null default now(),
    cost integer null default 0,
    constraint cart_items_pkey primary key (id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references carts (id),
    constraint cart_items_potion_id_fkey foreign key (potion_id) references potions (id)
  ) tablespace pg_default;

create table
  public.carts (
    id integer generated by default as identity,
    name text null,
    constraint carts_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.ledger (
    id bigint generated by default as identity,
    red_ml_change integer null default 0,
    green_ml_change integer null default 0,
    blue_ml_change integer null default 0,
    gold_change integer null default 0,
    constraint ledger_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.pot_ledgers (
    id bigint generated by default as identity,
    potion_id integer null,
    potions_changed integer null,
    constraint pot_ledgers_pkey primary key (id),
    constraint pot_ledgers_potion_id_fkey foreign key (potion_id) references potions (id)
  ) tablespace pg_default;

create table
  public.potions (
    id integer generated by default as identity,
    sku text null,
    num_red integer null,
    num_green integer null,
    num_blue integer null,
    num_dark integer null,
    price integer null,
    constraint potions_pkey primary key (id)
  ) tablespace pg_default;